// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Generates the byte-exact Router ledger migration checksum manifest.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use sha2::{Digest, Sha256};

const CARGO_MANIFEST_FILE: &str = "Cargo.toml";
const MIGRATIONS_DIRECTORY: &str = "src/ledger/migrations";
const SQLITE_VEC_DEPENDENCY_REQUIREMENT: &str = "=0.1.9";
const LIBM_DEPENDENCY_REQUIREMENT: &str = "=0.2.16";
const STATRS_DEPENDENCY_REQUIREMENT: &str = "=0.18.0";
const LIBM_EXP2_IMPLEMENTATION_ID: &str = "libm_0_2_16_exp2_force_soft_v1";
const STATRS_BETA_IMPLEMENTATION_ID: &str = "statrs_0_18_0_v1";
const STATRS_BETA_CDF_IMPLEMENTATION_ID: &str = "statrs_beta_cdf_0_18_0_v1";
const ACTIVE_MATH_SOURCE: &str = "src/active_math.rs";
const ACTIVE_MATH_BUILD_CONTRACT: &str = "build.rs";
const ACTIVE_MATH_BUILD_DOMAIN: &[u8] = b"nemo-relay-router/active-math-build/v1\0";
const STATRS_BUILD_ID_FIELD: &str = "statrs=0.18.0;default_features=false;features=[]";
const LIBM_BUILD_ID_FIELD: &str = "libm=0.2.16;default_features=false;features=[force-soft-floats]";

fn main() {
    let crate_directory =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest_path = crate_directory.join(CARGO_MANIFEST_FILE);
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={MIGRATIONS_DIRECTORY}");
    println!(
        "cargo:rustc-env=EXPECTED_VEC_VERSION={}",
        expected_vec_version(&manifest_path)
    );
    println!(
        "cargo:rustc-env=STATRS_BETA_IMPLEMENTATION_ID={}",
        statrs_beta_implementation_id(&manifest_path)
    );
    println!(
        "cargo:rustc-env=LIBM_EXP2_IMPLEMENTATION_ID={}",
        libm_exp2_implementation_id(&manifest_path)
    );
    println!(
        "cargo:rustc-env=STATRS_BETA_CDF_IMPLEMENTATION_ID={STATRS_BETA_CDF_IMPLEMENTATION_ID}"
    );
    println!("cargo:rerun-if-changed={ACTIVE_MATH_SOURCE}");
    println!("cargo:rerun-if-env-changed=CARGO_ENCODED_RUSTFLAGS");
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=RUSTC");
    println!("cargo:rerun-if-env-changed=TARGET");
    println!(
        "cargo:rustc-env=ACTIVE_MATH_BUILD_ID={}",
        active_math_build_id(&crate_directory)
    );

    let migrations = discover_migrations(Path::new(MIGRATIONS_DIRECTORY));
    let mut manifest = String::from(
        "// @generated by crates/router/build.rs\n\
         pub(crate) const MIGRATIONS: &[Migration] = &[\n",
    );
    for migration in migrations {
        manifest.push_str(&format!(
            "    Migration {{\n\
             \x20       version: {},\n\
             \x20       name: \"{}\",\n\
             \x20       checksum_sha256: \"{}\",\n\
             \x20       sql: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")),\n\
             \x20   }},\n",
            migration.version, migration.name, migration.checksum, migration.relative_path,
        ));
    }
    manifest.push_str("];\n");

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"))
        .join("router_migration_checksums.rs");
    fs::write(output, manifest).expect("write Router migration checksum manifest");
}

fn active_math_build_id(crate_directory: &Path) -> String {
    let active_math_source = sha256_hex(
        &fs::read(crate_directory.join(ACTIVE_MATH_SOURCE)).expect("read active-math source"),
    );
    let build_contract = sha256_hex(
        &fs::read(crate_directory.join(ACTIVE_MATH_BUILD_CONTRACT))
            .expect("read active-math build contract"),
    );
    let target = env::var("TARGET").expect("TARGET must be UTF-8");
    let rustc = env::var_os("RUSTC").expect("RUSTC");
    let rustc_output = Command::new(rustc)
        .arg("-vV")
        .output()
        .expect("run rustc -vV for active-math build identity");
    assert!(
        rustc_output.status.success(),
        "rustc -vV must succeed for active-math build identity"
    );
    let mut rustc_verbose =
        String::from_utf8(rustc_output.stdout).expect("rustc -vV output must be UTF-8");
    while matches!(rustc_verbose.as_bytes().last(), Some(b'\r' | b'\n')) {
        rustc_verbose.pop();
    }
    let encoded_rustflags = env::var("CARGO_ENCODED_RUSTFLAGS").unwrap_or_default();
    let profile = env::var("PROFILE").expect("PROFILE must be UTF-8");

    let mut digest = Sha256::new();
    digest.update(ACTIVE_MATH_BUILD_DOMAIN);
    for field in [
        active_math_source.as_str(),
        build_contract.as_str(),
        target.as_str(),
        rustc_verbose.as_str(),
        encoded_rustflags.as_str(),
        profile.as_str(),
        STATRS_BUILD_ID_FIELD,
        LIBM_BUILD_ID_FIELD,
    ] {
        let length = u32::try_from(field.len()).expect("active-math build field must fit u32");
        digest.update(length.to_be_bytes());
        digest.update(field.as_bytes());
    }
    hex_bytes(digest.finalize())
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex_bytes(Sha256::digest(bytes))
}

fn hex_bytes(bytes: impl AsRef<[u8]>) -> String {
    bytes
        .as_ref()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn statrs_beta_implementation_id(manifest_path: &Path) -> &'static str {
    let manifest_source =
        fs::read_to_string(manifest_path).expect("read Router Cargo package manifest");
    let manifest = manifest_source
        .parse::<toml::Table>()
        .expect("parse Router Cargo package manifest as TOML");
    let dependency = manifest
        .get("dependencies")
        .and_then(toml::Value::as_table)
        .and_then(|dependencies| dependencies.get("statrs"))
        .and_then(toml::Value::as_table)
        .expect("Router statrs dependency must be a dependency table");
    assert_eq!(
        dependency.get("version").and_then(toml::Value::as_str),
        Some(STATRS_DEPENDENCY_REQUIREMENT),
        "Router statrs dependency must remain exactly pinned"
    );
    assert_eq!(
        dependency
            .get("default-features")
            .and_then(toml::Value::as_bool),
        Some(false),
        "Router statrs dependency must keep default features disabled"
    );
    let features = dependency
        .get("features")
        .map(|value| {
            value
                .as_array()
                .expect("Router statrs features must be an array")
        })
        .map_or(&[][..], Vec::as_slice);
    assert!(
        features.is_empty(),
        "Router statrs dependency must not enable features"
    );
    STATRS_BETA_IMPLEMENTATION_ID
}

fn libm_exp2_implementation_id(manifest_path: &Path) -> &'static str {
    let manifest_source =
        fs::read_to_string(manifest_path).expect("read Router Cargo package manifest");
    let manifest = manifest_source
        .parse::<toml::Table>()
        .expect("parse Router Cargo package manifest as TOML");
    let dependency = manifest
        .get("dependencies")
        .and_then(toml::Value::as_table)
        .and_then(|dependencies| dependencies.get("libm"))
        .and_then(toml::Value::as_table)
        .expect("Router libm dependency must be a dependency table");
    assert_eq!(
        dependency.get("version").and_then(toml::Value::as_str),
        Some(LIBM_DEPENDENCY_REQUIREMENT),
        "Router libm dependency must remain exactly pinned"
    );
    assert_eq!(
        dependency
            .get("default-features")
            .and_then(toml::Value::as_bool),
        Some(false),
        "Router libm dependency must keep default features disabled"
    );
    let features = dependency
        .get("features")
        .and_then(toml::Value::as_array)
        .expect("Router libm dependency must declare features");
    assert_eq!(
        features.as_slice(),
        [toml::Value::String("force-soft-floats".to_string())],
        "Router libm dependency must enable only force-soft-floats"
    );
    LIBM_EXP2_IMPLEMENTATION_ID
}

fn expected_vec_version(manifest_path: &Path) -> String {
    let manifest_source =
        fs::read_to_string(manifest_path).expect("read Router Cargo package manifest");
    let manifest = manifest_source
        .parse::<toml::Table>()
        .expect("parse Router Cargo package manifest as TOML");
    let dependency = manifest
        .get("dependencies")
        .and_then(toml::Value::as_table)
        .and_then(|dependencies| dependencies.get("sqlite-vec"))
        .expect("Router sqlite-vec dependency must exist");
    let dependency_requirement = dependency.as_str().or_else(|| {
        dependency
            .as_table()
            .and_then(|dependency| dependency.get("version"))
            .and_then(toml::Value::as_str)
    });
    let dependency_requirement = dependency_requirement
        .expect("Router sqlite-vec dependency must have a string version requirement");
    assert_eq!(
        dependency_requirement, SQLITE_VEC_DEPENDENCY_REQUIREMENT,
        "Router sqlite-vec dependency must remain exactly pinned"
    );
    let package_version = dependency_requirement
        .strip_prefix('=')
        .expect("Router sqlite-vec dependency must use an exact requirement");
    format!("v{package_version}")
}

struct SourceMigration {
    version: i64,
    name: String,
    relative_path: String,
    checksum: String,
}

fn discover_migrations(directory: &Path) -> Vec<SourceMigration> {
    let mut paths = fs::read_dir(directory)
        .expect("read Router migrations directory")
        .map(|entry| entry.expect("read Router migration entry").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "sql"))
        .collect::<Vec<_>>();
    paths.sort();
    assert!(
        !paths.is_empty(),
        "Router must contain at least one migration"
    );

    paths
        .into_iter()
        .enumerate()
        .map(|(index, path)| load_migration(index, &path))
        .collect()
}

fn load_migration(index: usize, path: &Path) -> SourceMigration {
    println!("cargo:rerun-if-changed={}", path.display());
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .expect("Router migration file name must be UTF-8");
    let name = file_name
        .strip_suffix(".sql")
        .expect("Router migration must use the .sql extension");
    let (version_text, description) = name
        .split_once('_')
        .expect("Router migration name must be NNNN_description.sql");
    assert!(
        version_text.len() == 4 && version_text.bytes().all(|byte| byte.is_ascii_digit()),
        "Router migration version must contain four decimal digits"
    );
    assert!(
        !description.is_empty()
            && description
                .bytes()
                .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_'),
        "Router migration description must use lowercase ASCII, digits, and underscores"
    );
    let version = version_text
        .parse::<i64>()
        .expect("Router migration version must fit i64");
    let expected_version = i64::try_from(index + 1).expect("Router migration count must fit i64");
    assert_eq!(
        version, expected_version,
        "Router migration versions must be contiguous and start at 0001"
    );

    let sql = fs::read(path).expect("read Router migration SQL");
    assert!(
        !sql.contains(&b'\r'),
        "Router migration SQL must use canonical LF line endings"
    );
    assert!(
        sql.ends_with(b"\n"),
        "Router migration SQL must end with a newline"
    );
    let checksum = Sha256::digest(&sql)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    let relative_path = path
        .to_str()
        .expect("Router migration path must be UTF-8")
        .replace('\\', "/");

    SourceMigration {
        version,
        name: name.to_string(),
        relative_path,
        checksum,
    }
}
