// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Stable, non-secret Router eligibility reason codes.

/// One reason a call or candidate cannot participate in routing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum IneligibilityReason {
    NonPrimary,
    Streaming,
    Stateful,
    MissingReplay,
    ReplayVersionMismatch,
    ReplayFamilyMismatch,
    ReplayIdentityInvalid,
    MissingModel,
    NoMatchingPool,
    AmbiguousPool,
    CodecDecode,
    CodecRoundTrip,
    UnsupportedInstructions,
    UnsupportedResponseFormat,
    UnsupportedProviderRepresentation,
    UnsupportedContractSchema,
    NonLocalContractReference,
    InvalidContractSchema,
    InvalidToolContract,
    ProjectionFailed,
    CanonicalProjection,
    CanonicalMissingTask,
    CanonicalMultimodal,
    CanonicalInstructionBound,
    CanonicalTaskBound,
    CanonicalContextBound,
    CanonicalSchemaFingerprint,
    CanonicalCapabilities,
    CanonicalPositionFeatures,
    CanonicalSerialization,
    ResponsesContinuation,
    ResponsesStore,
    CandidateCapability,
    ContextLimitUnprovable,
    ContextLimitExceeded,
    CandidateRewrite,
    NoCandidates,
    SamplingFailed,
    IntentCapacity,
    QueueFull,
    RuntimeFailure,
}

impl IneligibilityReason {
    /// Return the stable diagnostic code without request or provider details.
    pub(crate) const fn code(self) -> &'static str {
        match self {
            Self::NonPrimary => "router.ineligible.non_primary",
            Self::Streaming => "router.ineligible.streaming",
            Self::Stateful => "router.ineligible.stateful",
            Self::MissingReplay => "router.ineligible.missing_replay",
            Self::ReplayVersionMismatch => "router.ineligible.replay_version",
            Self::ReplayFamilyMismatch => "router.ineligible.replay_family",
            Self::ReplayIdentityInvalid => "router.ineligible.replay_identity",
            Self::MissingModel => "router.ineligible.missing_model",
            Self::NoMatchingPool => "router.ineligible.no_matching_pool",
            Self::AmbiguousPool => "router.runtime.ambiguous_pool",
            Self::CodecDecode => "router.ineligible.codec_decode",
            Self::CodecRoundTrip => "router.ineligible.codec_round_trip",
            Self::UnsupportedInstructions => "router.ineligible.instructions",
            Self::UnsupportedResponseFormat => "router.ineligible.response_format",
            Self::UnsupportedProviderRepresentation => "router.ineligible.provider_representation",
            Self::UnsupportedContractSchema => "router.ineligible.contract_schema_draft",
            Self::NonLocalContractReference => "router.ineligible.contract_schema_reference",
            Self::InvalidContractSchema => "router.ineligible.contract_schema_invalid",
            Self::InvalidToolContract => "router.ineligible.tool_contract",
            Self::ProjectionFailed => "router.ineligible.projection",
            Self::CanonicalProjection => "router.ineligible.canonical_projection",
            Self::CanonicalMissingTask => "router.ineligible.canonical_missing_task",
            Self::CanonicalMultimodal => "router.ineligible.canonical_multimodal",
            Self::CanonicalInstructionBound => "router.ineligible.canonical_instruction_bound",
            Self::CanonicalTaskBound => "router.ineligible.canonical_task_bound",
            Self::CanonicalContextBound => "router.ineligible.canonical_context_bound",
            Self::CanonicalSchemaFingerprint => "router.ineligible.canonical_schema_fingerprint",
            Self::CanonicalCapabilities => "router.ineligible.canonical_capabilities",
            Self::CanonicalPositionFeatures => "router.ineligible.canonical_position_features",
            Self::CanonicalSerialization => "router.ineligible.canonical_serialization",
            Self::ResponsesContinuation => "router.ineligible.responses_continuation",
            Self::ResponsesStore => "router.ineligible.responses_store",
            Self::CandidateCapability => "router.ineligible.candidate_capability",
            Self::ContextLimitUnprovable => "router.ineligible.context_limit_unprovable",
            Self::ContextLimitExceeded => "router.ineligible.context_limit_exceeded",
            Self::CandidateRewrite => "router.ineligible.candidate_rewrite",
            Self::NoCandidates => "router.ineligible.no_candidates",
            Self::SamplingFailed => "router.runtime.sampling_failed",
            Self::IntentCapacity => "router.runtime.intent_capacity",
            Self::QueueFull => "router.runtime.queue_full",
            Self::RuntimeFailure => "router.runtime.failure",
        }
    }
}
