// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const declarationsPath = path.join(__dirname, 'index.d.ts');
const generatedMarker = /\/\* auto-generated by NAPI-RS \*\/\r?\n/;
const replayTypeMarker = 'export type LlmReplayFactory =';
const privateReplayTestDeclaration =
  /(?:\/\*\*(?:[^*]|\*(?!\/))*\*\/\r?\n)?export declare function __testNodeReplayBridge[^\r\n]*(?:\r?\n|$)/;
const privateRouterProbeDeclaration =
  /(?:\/\*\*(?:[^*]|\*(?!\/))*\*\/\r?\n)?export declare function __routerNativeVectorProbe[^\r\n]*(?:\r?\n|$)/;
const replayTypes = `
/** JSON-compatible primitive value. */
export type JsonPrimitive = null | boolean | number | string
/** JSON-compatible value accepted and returned by the native binding. */
export type Json = JsonPrimitive | Array<Json> | { [key: string]: Json }
/** Recursively immutable JSON value passed to replay factories and callables. */
export type DeepReadonlyJson =
  | JsonPrimitive
  | ReadonlyArray<DeepReadonlyJson>
  | { readonly [key: string]: DeepReadonlyJson }
/** Provider request/response family for a V2 managed LLM call. */
export type LlmApiFamily = 'openai_chat_completions' | 'openai_responses' | 'anthropic_messages'
/** Execution role for a V2 managed LLM call. */
export type LlmCallRole = 'primary' | 'shadow' | 'judge'
/** One immutable scope in the trajectory owner-to-parent path. */
export interface LlmTrajectoryScope {
  readonly uuid: string
  readonly name: string
  readonly scopeType: string
}
/** Frozen routing context passed to a V2 replay factory. */
export interface LlmExecutionContext {
  readonly callUuid: string
  readonly rootUuid: string
  readonly parentUuid: string
  readonly trajectoryOwnerUuid: string
  readonly trajectoryOwnerPath: ReadonlyArray<LlmTrajectoryScope>
  readonly apiFamily: LlmApiFamily
  readonly callRole: LlmCallRole
  readonly attributes: number
  readonly tenantId: string | null
  readonly agentId: string | null
  readonly sanitizedMetadata: { readonly [key: string]: DeepReadonlyJson }
}
/** One independently cancellable Node replay invocation. */
export interface LlmReplayInvocation {
  readonly result: Promise<Json>
  readonly cancel: () => void
}
/** Async callable retained by a V2 replay transport. */
export type LlmReplayCallable = (request: DeepReadonlyJson) => LlmReplayInvocation
/** Immutable transport descriptor returned by a V2 replay factory.
 * Non-enumerable or symbol-keyed binding-private fields are retained.
 */
export interface LlmReplayDescriptor {
  readonly [key: symbol]: unknown
  readonly contractVersion: number
  readonly apiFamily: LlmApiFamily
  readonly transportIdentity: string
  readonly replay: LlmReplayCallable
}
/** Synchronous factory for one call-scoped replay transport. */
export type LlmReplayFactory = (context: LlmExecutionContext) => LlmReplayDescriptor
`;

const declarations = fs.readFileSync(declarationsPath, 'utf8');
let updated = declarations.replace(privateReplayTestDeclaration, '').replace(privateRouterProbeDeclaration, '');
if (!updated.includes(replayTypeMarker)) {
  if (!generatedMarker.test(declarations)) {
    throw new Error(`NAPI-RS declaration marker not found in ${declarationsPath}`);
  }
  updated = updated.replace(generatedMarker, (marker) => `${marker}${replayTypes}\n`);
}
if (updated !== declarations) {
  fs.writeFileSync(declarationsPath, updated);
}
